# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chomeur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_chomeur', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_expertise', models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('expert', 'Expert')], default='débutant', max_length=20)),
                ('solde_jetons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chomeur',
            },
        ),
        migrations.CreateModel(
            name='ChomeurCompetence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('expert', 'Expert')], default='débutant', max_length=20)),
            ],
            options={
                'db_table': 'chomeur_competence',
            },
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_exploit', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'exploit',
            },
        ),
    ]
