# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chomeur', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chomeur',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chomeurs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chomeur',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chomeurs_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chomeur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_chomeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chomeurcompetence',
            name='chomeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chomeur.chomeur'),
        ),
        migrations.AddField(
            model_name='chomeurcompetence',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competence'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='chomeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chomeur.chomeur'),
        ),
        migrations.AlterUniqueTogether(
            name='chomeurcompetence',
            unique_together={('chomeur', 'competence')},
        ),
    ]
