# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_admin', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('niveau_autorisation', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_validation', 'Admin Validation'), ('admin_moderation', 'Admin Modération')], default='admin_moderation', max_length=30)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
    ]
