# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
