# Generated by Django 5.2.8 on 2025-11-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_initial'),
        ('chomeur', '0003_rename_date_creation_exploit_date_publication_and_more'),
        ('recruteur', '0002_alter_offre_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_demande', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type_verification', models.CharField(choices=[('identite', 'identite'), ('localisation', 'localisation'), ('competences', 'competences'), ('entreprise', 'entreprise'), ('complete', 'complete')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'en_attente'), ('en_cours', 'en_cours'), ('approuvee', 'approuvee'), ('refusee', 'refusee')], default='en_attente', max_length=50)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_created_set', to=settings.AUTH_USER_MODEL)),
                ('id_admin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_responsable', to='administrateur.administrateur')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_verification', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demande_verification',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_historique', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type_action', models.CharField(choices=[('validation_compte', 'validation_compte'), ('refus_compte', 'refus_compte'), ('suspension', 'suspension'), ('reactivation', 'reactivation'), ('modification_profil', 'modification_profil'), ('suppression_contenu', 'suppression_contenu')], max_length=50)),
                ('table_concernee', models.CharField(blank=True, max_length=50, null=True)),
                ('id_enregistrement', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_admin', to='administrateur.administrateur')),
                ('id_utilisateur_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_cible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historique_validation',
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_piece', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type_piece', models.CharField(choices=[('passeport', 'passeport'), ('carte_identite', 'carte_identite'), ('permis_conduire', 'permis_conduire'), ('justificatif_domicile', 'justificatif_domicile'), ('diplome', 'diplome'), ('certificat_travail', 'certificat_travail'), ('autre', 'autre')], max_length=50)),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier_url', models.CharField(max_length=255)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('pays_emission', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_verification', models.CharField(choices=[('en_attente', 'en_attente'), ('approuve', 'approuve'), ('refuse', 'refuse'), ('expire', 'expire')], default='en_attente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_created_set', to=settings.AUTH_USER_MODEL)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'piece_justificative',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_signalement', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type_signalement', models.CharField(choices=[('profil_frauduleux', 'profil_frauduleux'), ('contenu_inapproprie', 'contenu_inapproprie'), ('spam', 'spam'), ('harcelement', 'harcelement'), ('fausse_offre', 'fausse_offre'), ('autre', 'autre')], max_length=50)),
                ('description', models.TextField()),
                ('preuves_url', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'en_attente'), ('en_cours', 'en_cours'), ('traite', 'traite'), ('rejete', 'rejete')], default='en_attente', max_length=50)),
                ('decision', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalement_created_set', to=settings.AUTH_USER_MODEL)),
                ('id_admin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalement_admin_responsable', to='administrateur.administrateur')),
                ('id_exploit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_exploit', to='chomeur.exploit')),
                ('id_offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_offre', to='recruteur.offre')),
                ('id_signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_signaleur', to=settings.AUTH_USER_MODEL)),
                ('id_utilisateur_signale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_utilisateur', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalement_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signalement',
            },
        ),
        migrations.CreateModel(
            name='VerificationLocalisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_verification', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('adresse_complete', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('justificatif_url', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'en_attente'), ('verifie', 'verifie'), ('refuse', 'refuse')], default='en_attente', max_length=50)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifloc_created_set', to=settings.AUTH_USER_MODEL)),
                ('id_admin_verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifloc_admin', to='administrateur.administrateur')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_localisation', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifloc_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_localisation',
            },
        ),
    ]
