# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_recruteur', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type_recruteur', models.CharField(choices=[('individuel', 'Individuel'), ('entreprise', 'Entreprise')], default='entreprise', max_length=20)),
                ('nom_entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('site_web', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_employes', models.IntegerField(blank=True, null=True)),
                ('solde_jetons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruteurs_crees', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruteurs_modifies', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_recruteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruteur',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_offre', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type_contrat', models.CharField(max_length=50)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='active', max_length=30)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.recruteur')),
            ],
            options={
                'db_table': 'offre',
            },
        ),
        migrations.CreateModel(
            name='TestCompetence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_test', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('question', models.TextField()),
                ('reponse_correcte', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competence')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.offre')),
            ],
            options={
                'db_table': 'test_competence',
            },
        ),
        migrations.CreateModel(
            name='OffreCompetence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('niveau_requis', models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('expert', 'Expert')], default='intermédiaire', max_length=20)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competence')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.offre')),
            ],
            options={
                'db_table': 'offre_competence',
                'unique_together': {('offre', 'competence')},
            },
        ),
    ]
