# Generated by Django 5.2.8 on 2025-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Fermée')], default='active', max_length=30),
        ),
    ]
