# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chomeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_competence', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competence',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_evaluation', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('type_evaluation', models.CharField(choices=[('recruteur_vers_chomeur', 'Recruteur vers Chômeur'), ('chomeur_vers_recruteur', 'Chômeur vers Recruteur')], max_length=50)),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='TransactionJeton',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_transaction', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('montant', models.IntegerField()),
                ('type_transaction', models.CharField(choices=[('achat', 'Achat'), ('gain_test', 'Gain test'), ('postulation', 'Postulation'), ('remboursement', 'Remboursement'), ('bonus', 'Bonus'), ('depense_service', 'Dépense service')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_jeton',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_utilisateur', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('recruteur', 'Recruteur'), ('chomeur', 'Chômeur')], max_length=20)),
                ('photo_profil', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('statut_verifie', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creations', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_candidature', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('lettre_motivation', models.TextField(blank=True, null=True)),
                ('cv_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('date_postulation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('vue', 'Vue'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('entretien', 'Entretien')], default='en_attente', max_length=30)),
                ('jetons_utilises', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chomeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chomeur.chomeur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_creees', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidature',
            },
        ),
    ]
