# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chomeur', '0002_initial'),
        ('core', '0001_initial'),
        ('recruteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.offre'),
        ),
        migrations.AddField(
            model_name='competence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competence',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='candidature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidature'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='chomeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chomeur.chomeur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='recruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.recruteur'),
        ),
        migrations.AddField(
            model_name='transactionjeton',
            name='candidature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidature'),
        ),
        migrations.AddField(
            model_name='transactionjeton',
            name='chomeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chomeur.chomeur'),
        ),
        migrations.AddField(
            model_name='transactionjeton',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionjeton',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionjeton',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruteur.recruteur'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('chomeur', 'offre')},
        ),
    ]
